import 'package:flutter/material.dart';

import 'package:flutteryomi/presentation/theme/colorscheme/base_color_scheme.dart';

/// Colors for Green Apple theme
/// Original color scheme by CarlosEsco, Jays2Kings and CrepeTF
/// M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
///
/// Key colors:
/// Primary #188140
/// Secondary #188140
/// Tertiary #D33131
/// Neutral #5D5F5B
class GreenAppleColorScheme extends BaseColorScheme {
  @override
  final ColorScheme darkScheme = const ColorScheme.dark(
    primary: Color(0xFF7ADB8F),
    onPrimary: Color(0xFF003915),
    primaryContainer: Color(0xFF005322),
    onPrimaryContainer: Color(0xFF96F8A9),
    inversePrimary: Color(0xFF006D2F),
    secondary: Color(0xFF7ADB8F),
    onSecondary: Color(0xFF003915),
    secondaryContainer: Color(0xFF005322),
    onSecondaryContainer: Color(0xFF96F8A9),
    tertiary: Color(0xFFFFB3AA),
    onTertiary: Color(0xFF680006),
    tertiaryContainer: Color(0xFF93000D),
    onTertiaryContainer: Color(0xFFFFDAD5),
    background: Color(0xFF1A1C19),
    onBackground: Color(0xFFE1E3DD),
    surface: Color(0xFF1A1C19),
    onSurface: Color(0xFFE1E3DD),
    surfaceVariant: Color(0xFF414941),
    onSurfaceVariant: Color(0xFFC1C8BE),
    surfaceTint: Color(0xFF7ADB8F),
    inverseSurface: Color(0xFFE1E3DD),
    onInverseSurface: Color(0xFF1A1C19),
    outline: Color(0xFF8B9389),
  );

  @override
  final ColorScheme lightScheme = const ColorScheme.light(
    primary: Color(0xFF0058CA),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD9E2FF),
    onPrimaryContainer: Color(0xFF001945),
    inversePrimary: Color(0xFFB0C6FF),
    secondary: Color(0xFF0058CA),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD9E2FF),
    onSecondaryContainer: Color(0xFF001945),
    tertiary: Color(0xFF006E1B),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFF95F990),
    onTertiaryContainer: Color(0xFF002203),
    background: Color(0xFFFEFBFF),
    onBackground: Color(0xFF1B1B1F),
    surface: Color(0xFFFEFBFF),
    onSurface: Color(0xFF1B1B1F),
    surfaceVariant: Color(0xFFE1E2EC),
    onSurfaceVariant: Color(0xFF44464F),
    surfaceTint: Color(0xFF0058CA),
    inverseSurface: Color(0xFF303034),
    onInverseSurface: Color(0xFFF2F0F4),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF410002),
    outline: Color(0xFF757780),
    outlineVariant: Color(0xFFC5C6D0),
  );
}
